import numpy as np
import pandas as pd
import requests

URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

#Exercise 1 -# Extract tables from webpage using Pandas. Retain table number 3 as the required dataframe.
#1.1 Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
#1.2 Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
#1.3 Assign column names as "Country" and "GDP (Million USD)"

response = requests.get(URL)

tables=pd.read_html(response.text)
df=tables[2]


df1=df.iloc[:,[0,2]]
            
df2=df1.iloc[0:9,:]

df2.columns = ['Country','GDP (Million USD)']



#Exercise 2 -# Modify the GDP column of the DataFrame, converting the value available in Million USD to Billion USD.
#Use the round() method of Numpy library to round the value to 2 decimal places. Modify the header of the DataFrame to GDP (Billion USD)
#2.1 Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method
#2.2 Convert the GDP value in Million USD to Billion USD
#2.3 Use numpy.round() method to round the value to 2 decimal places.
#2.4 Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'


df3=df2
df3['GDP (Million USD)'] = df2['GDP (Million USD)'].astype(int)

df3['GDP (Million USD)'] = df3['GDP (Million USD)']/1000

df3.columns = ['Country','GDP (Billion USD)']

df3['GDP (Billion USD)'] = np.round(df3['GDP (Billion USD)'],2)



#Exercise 3 -# Load the DataFrame to the CSV file named "Largest_economies.csv"

#df3. to_csv('Largest_economies.csv', index=False)